services:

  # API
  api:
    build: .
    container_name: webcrawler-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
      ES_URI: http://elasticsearch:9200
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - crawler-net

  # MongoDB
  mongo:
    image: mongo:7
    container_name: webcrawler-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - crawler-net

  # ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: webcrawler-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s    
    restart: unless-stopped
    networks:
      - crawler-net

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: webcrawler-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    networks:
      - crawler-net

# Volumes
volumes:
  mongo-data:
  es-data:
  rabbitmq-data:

# Rede
networks:
  crawler-net:
    driver: bridge
